apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world-monitor
  labels:
    k8s-app: prometheus
spec:
  selector:
    matchLabels:
      app: hello-world
  endpoints:
    - port: web
      interval: 5s
