kind: Service
apiVersion: v1
metadata:
  name: hello-world-istio 
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - name: web
    port: 8080
  - name: metrics
    port: 8000
  type: LoadBalancer
